# Generated by Django 3.2.13 on 2022-05-11 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220506_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=30, null=True)),
                ('ticket_id', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('available_count', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_id', models.CharField(blank=True, max_length=30, null=True)),
                ('canceled', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 11, 19, 53, 23, 716994, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 5, 11, 19, 53, 23, 717012, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='webhookmessage',
            name='recieved_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 19, 53, 23, 714144, tzinfo=utc), help_text='When message has recieved.'),
        ),
    ]
