# Generated by Django 3.2.13 on 2022-05-11 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220511_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='webhookmessage',
            name='recieved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When message has recieved.'),
        ),
    ]
