# Generated by Django 3.2.13 on 2022-05-11 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_attendee'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhookmessage',
            name='core_webhoo_recieve_ae426b_idx',
        ),
        migrations.RemoveField(
            model_name='webhookmessage',
            name='recieved_at',
        ),
        migrations.AddField(
            model_name='webhookmessage',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When message has received.'),
        ),
        migrations.AddIndex(
            model_name='webhookmessage',
            index=models.Index(fields=['received_at'], name='core_webhoo_receive_dfeb5f_idx'),
        ),
    ]
